### ISSUE TITLE
Cannot save Digital Product types

### ISSUE THREAD

**Issue by grego3** [pixelandtonic/DigitalProducts#11]
I created a digital product type. When I try to make changes to its settings or product fields, I receive the follow PHP error:

**Fatal error:** Class Craft\DigitalProducts_ProductModel contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Commerce\Interfaces\Purchasable::getShippingCategoryId, Commerce\Interfaces\Purchasable::getIsAvailable, Commerce\Interfaces\Purchasable::populateLineItem) in **/sync/zift/craft/plugins/digitalproducts/models/DigitalProducts_ProductModel.php** on line **318**

I am using Craft Commerce v1.2.1327 with Craft CMS v2.6.2950. My server is running PHP 5.6.4.

**Comment by angrybrad** [comment]
Are you on the latest 1.0.2 version of Digital Products?

**Comment by grego3** [comment]
I was not. I updated and it seems to be working correctly.

Is there any reason that this wasn't showing as an available update through the CMS?

**Comment by lukeholder** [comment]
@grego3 We just released 1.0.3 which adds support for Craft update notifications in your Craft CP.
