### ISSUE TITLE
Digital products pricing

### ISSUE THREAD

**Issue by Floriswijgergangs** [pixelandtonic/DigitalProducts#12]
When I give a digital product an pricing of € 12.50 and view it again after saving it shows 12,50. When you save it again it becomes € 12. 
In Craft Commerce products it's okey.

**Comment by conormcafee** [comment]
When I go to edit a product after save the price changes.

For example, the product I saved was £1200, however if I go back in and make a change it changes to £1. This is happening with all Digital Products

**Comment by conormcafee** [comment]
Thanks @andris-sevcenko 👍🏼
