### ISSUE TITLE
Craft\DigitalProducts_ProductModel and its behaviors do not have a method or closure named "variants".

### ISSUE THREAD

**Issue by johnj24** [pixelandtonic/DigitalProducts#15]
I had started a new project using Commerce with a handful of products and have now switched them entirely over to Digital Downloads. I'm trying to use the same template as when they were standard Commerce products, so perhaps thats the issue. Should anything change?

The error I now get is: "Craft\DigitalProducts_ProductModel and its behaviors do not have a method or closure named "variants"."

Looking for some advice. Thanks!

**Comment by brandonkelly** [comment]
Right, variants are a Product-specific feature. Digital Products don’t have them.

**Comment by johnj24** [comment]
I'm not using any variants anywhere. Something is obviously very easy, but I'm missing it. First time using Digital Products. What should be done to show a product _entry page?

**Comment by lukeholder** [comment]
John, somewhere in your templates you are referencing a variant from your digital product model.

Look for twig code that looks something like this:

`{{ for variant in product.variants }}` or `{{ product.variant.price }}`

If you are using the example templates, they have been built for regular products with variants so there will quite a few places you will need to change to get them to work with other purchasables like digital products.

**Comment by johnj24** [comment]
I hit find+replace with the word "variant" and it didn't yield any results the first time. I promise :)

**Comment by brandonkelly** [comment]
@johnj24 Can you search for the error in `craft/storage/runtime/logs/craft.log` (or one of the `craft.log.X` files)? Then find the stack trace that follows it, and post it here.
