### ISSUE TITLE
Is the field handle "description" a reserved word in Digital Products?

### ISSUE THREAD

**Issue by johnj24** [pixelandtonic/DigitalProducts#16]
I have a field with the handle 'description'. In my template, I call that field using {{ product.description }}, but all it does is spit out the Title. I can confirm there are actual sentences within the 'description' field that it should be displaying. I've also changed the 'description' field to 'pDescription' and, after the change, the field shows the correct information.

Seems like the 'description' field handle is a reserved word?

**Comment by lukeholder** [comment]
Description is a reserved field name on all purchasables at the moment. Will look to review this in Commerce 2. For now you will need to use a different field name for your custom field. Thanks.
