### ISSUE TITLE
Navigation active state incorrect in submenu

### ISSUE THREAD

**Issue by astuteo** [pixelandtonic/DigitalProducts#19]
Clicking on "Settings" in the Digital Products subnavigation does not show the correct active nav state for the URL. It goes to the correct page, but highlights "Products" instead.

**Comment by lukeholder** [comment]
Thanks, fixed for the next release

**Comment by lukeholder** [comment]
c534d48c00fe15ac0277095022e745c03b8e11d6

**Comment by lukeholder** [comment]
https://github.com/craftcms/commerce-digital-products/commit/c534d48c00fe15ac0277095022e745c03b8e11d6
