### ISSUE TITLE
Changing status of license is not saved when making changes in CP

### ISSUE THREAD

**Issue by monachilada** [pixelandtonic/DigitalProducts#2]
Changing the value in the dropdown labeled "Status" when editing a license, is not persistent after saving the license. Changing the value for "Enabled", on the right hand side does work, and also changes the value displayed in "Status", however, see #1 for how that's handled incorrectly on the front end.

**Comment by andris-sevcenko** [comment]
Fixed in 4cdd20f0ab9a3977df8e54bd2869dbf990da1d66
