### ISSUE TITLE
Allow settings to configure when a license will expire

### ISSUE THREAD

**Issue by monachilada** [pixelandtonic/DigitalProducts#3]
It would be great to be able to set a license to expire after a certain time frame, or under other variable circumstances such as the release of a new software version or support being dropped for an older version of software.

**Comment by andris-sevcenko** [comment]
A lot of the potential use-cases can be covered by using the existing hooks or, for example, having a custom Version fieldtype. We're currently debating adding an expiryDate field that you can use for license expiration purposes, however.

With that you should have everything you need to implement various expiration scenarios without needlessly increasing the complexity of the plugin.

**Comment by medoingthings** [comment]
Definitely +1
