### ISSUE TITLE
Type missing from product data?

### ISSUE THREAD

**Issue by arthurdewolf** [pixelandtonic/DigitalProducts#7]
With regular Craft Commerce products I can get the Product Type with `{{ product.type }}` but this seems to be missing from digital products. There is typeId but I would like to use the Product Type handle. Could this be added? Thank you.

**Comment by lukeholder** [comment]
There was always a `.productType` but have gone ahead and added a `.type` as an alias:

https://github.com/pixelandtonic/DigitalProducts/commit/0d977cbf0265002b7f5f4d481566af3291a9b3de

is in the latest 1.0.1 release.
