### ISSUE TITLE
Craft\Commerce_TaxCategoryModel behaviors no method or closure with name "optgroup".

### ISSUE THREAD

**Issue by Floriswijgergangs** [pixelandtonic/DigitalProducts#9]
Getting this error after installing Craft CMS - Craft Commerce and Digital products. 
Is it something with the whole new Commerce 1.2?
It happends when I click + New product in the digital products section 

![image](https://cloud.githubusercontent.com/assets/8255580/19302065/e87d0e88-9062-11e6-9f42-ea9f8a97d540.png)

**Comment by lukeholder** [comment]
Sorry about that, you can update the latest release 1.0.2 with the fix: https://github.com/pixelandtonic/DigitalProducts/releases

**Comment by Floriswijgergangs** [comment]
Updated to 1.0.2. but still getting the same error.

**Comment by lukeholder** [comment]
Can you clear your templates cache from the control panel for me?

Can you also confirm you see in line 59 of `plugins/digitalproducts/templates/products/_fields.html` this code after updating to 1.0.2:

```
options: craft.commerce.getTaxCategories(true)
```

**Comment by Floriswijgergangs** [comment]
Auch, I reinstalled it, but the cache.., Sorry for that one. It works. Thanks!

**Comment by lukeholder** [comment]
No worries, glad it's working for you!
